module ChangeLog

    let version = "1.3.1"
    let changelog =
        [
            "1.3.1 - 2020-07-26"
            "Added"
                "Docker images"
                "Web tests and run on docker image"
            "Changed"
                "Simpler webpack setup."
                "Update Changelog format"
            "Removed"
                "Azure deployment"
            "1.3.0 - 2020-07-20"
            "Added"
                "Turbolinks support"
                "Html views rendered in backend"
                "Simple frontend scripts for interactivity"
            "Removed"
                "Elmish SPA"
            "1.2.0 - 2019-11-28"
            "Changed"
                "Refactor frontend model to use a flat model"
                "Make the api more generic cmd/queries"
            "1.1.0 - 2019-10-26"
            "Changed"
                "Build script: tag-handling"
                "Remove local nuget source in build script."
            "1.0.0 - 2019-10-16"
            "Added"
                "List chickens"
                "Add/remove eggs"
        ]
