module ChickenCheck.Backend.Bundle

    // Autogenerated from build.fsx, any changes will be overwritten on build!

    open Feliz.ViewEngine
    let bundle =
        [
            Html.script [ prop.src "ChickenCheck.runtime.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.vendor.base64-js.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.vendor.buffer.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.vendor.core-js.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.vendor.css-loader.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.vendor.fortawesome.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.vendor.ieee754.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.vendor.isarray.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.vendor.style-loader.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.vendor.turbolinks.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.vendor.webpack.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.app.js"; prop.defer true ]
            Html.script [ prop.src "ChickenCheck.style.js"; prop.defer true ]
        ]
