module ChickenCheck.Backend.Bundle

// Autogenerated from build.fsx, any changes will be overwritten on build!

open Feliz.ViewEngine
let bundle =
        [
        Html.script [ prop.src "ChickenCheck.runtime.220c41254cc3184d7d18.js"; prop.defer true ]
        Html.script [ prop.src "ChickenCheck.vendor.base64-js.c534a67c3747b50f81b5.js"; prop.defer true ]
        Html.script [ prop.src "ChickenCheck.vendor.buffer.4bc5d3414f15299e537c.js"; prop.defer true ]
        Html.script [ prop.src "ChickenCheck.vendor.bulma-calendar.961eedced820bce25ed9.js"; prop.defer true ]
        Html.script [ prop.src "ChickenCheck.vendor.core-js.9d1fc024d53217e539e6.js"; prop.defer true ]
        Html.script [ prop.src "ChickenCheck.vendor.ieee754.b4ddc1c0cda58ea31725.js"; prop.defer true ]
        Html.script [ prop.src "ChickenCheck.vendor.isarray.6f47c1d9c943dcdbefcc.js"; prop.defer true ]
        Html.script [ prop.src "ChickenCheck.vendor.turbolinks.ebed4d9f47169d882d78.js"; prop.defer true ]
        Html.script [ prop.src "ChickenCheck.vendor.webpack.c7c69cbabc629065e060.js"; prop.defer true ]
        Html.script [ prop.src "ChickenCheck.app.4f9b9bd087e6024f1109.js"; prop.defer true ]
        Html.link [ prop.rel "stylesheet"; prop.href "0.style.7b791af26b8e8aca9cdf.css" ]
    ]
